#Chapter 1

In [0]:
a = 2
b = 4

In [2]:
c = (a**2 + b**2) ** 0.5
print(c)

4.47213595499958


Executing the above equation with callable function

In [3]:
p = lambda a, b: (a**2 + b**2) ** 0.5
p(2,4)

4.47213595499958

# Chapter 2

In [0]:
a = [3.0, 4.0, 2.0]

In [5]:
a[0]

3.0

In [6]:
a[2] = 3.0
a

[3.0, 4.0, 3.0]

In [7]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [8]:
a[1]


tensor(1.)

In [9]:
float(a[1])


1.0

In [10]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [12]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

In [13]:
float(points[0]), float(points[1])


(1.0, 4.0)

In [14]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [18]:
points[0, 1]


tensor(4.)

In [19]:
points[0]

tensor([1., 4.])

In [20]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()


 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [21]:
points_storage = points.storage()
points_storage[0]

1.0

In [22]:
points.storage()[1]

4.0

In [23]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [24]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()


2

In [25]:
second_point.size()

torch.Size([2])

In [26]:
second_point.shape

torch.Size([2])

In [27]:
points.stride()

(2, 1)

In [28]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [29]:
second_point.storage_offset()

2

In [30]:
second_point.stride()


(1,)

In [31]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [32]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [33]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [34]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [35]:
id(points.storage()) == id(points_t.storage())


True

In [36]:
points.stride()

(2, 1)

In [37]:
points_t.stride()


(1, 2)

In [38]:
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([3, 4, 5])

In [39]:
some_tensor.stride()

(20, 5, 1)

In [40]:
some_tensor.stride()

(20, 5, 1)

In [41]:
points.is_contiguous()

True

In [42]:
points_t.is_contiguous()

False

In [43]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [44]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [45]:
points_t.stride()

(1, 2)

In [46]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [47]:
points_t_cont.stride()


(3, 1)

In [48]:
points_t_cont.storage()


 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [50]:
short_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)


In [0]:
points = torch.randn(10, 2)
short_points = points.type(torch.short)

In [54]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [55]:
points[1:]
points[1:, :]
points[1:, 0] 

tensor([ 1.3018,  1.7055,  1.3694,  2.2717,  0.0891,  1.1480,  0.8232, -0.9806,
        -0.5962])

In [56]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:
points = torch.from_numpy(points_np)

In [58]:
torch.save(points, '../data/p1ch3/ourpoints.t')

FileNotFoundError: ignored

In [59]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
 torch.save(points, f)

FileNotFoundError: ignored

In [0]:
points = torch.load('../data/p1ch3/ourpoints.t')


In [60]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
 points = torch.load(f)

FileNotFoundError: ignored

In [61]:
import h5py
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

OSError: ignored

In [62]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[1:]

OSError: ignored

In [63]:
last_points = torch.from_numpy(dset[1:])
f.close()
>>> last_points = torch.from_numpy(dset[1:])


SyntaxError: ignored

In [0]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]],
device='cuda')

In [0]:
points_gpu = points.to(device='cuda')

In [0]:
points_gpu = points.to(device='cuda:0')

In [0]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')

In [0]:
points_gpu = points_gpu + 4

In [0]:
points_cpu = points_gpu.to(device='cpu')

In [0]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()


In [0]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

In [0]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

In [0]:
a = torch.ones(3, 2)


In [74]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])