In [133]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


#Chapter 1

In [0]:
a = 2
b = 4

In [135]:
c = (a**2 + b**2) ** 0.5
print(c)

4.47213595499958


Executing the above equation with callable function

In [136]:
p = lambda a, b: (a**2 + b**2) ** 0.5
p(2,4)

4.47213595499958

# Chapter 2

In [0]:
a = [3.0, 4.0, 2.0]

In [79]:
a[0]

3.0

In [138]:
a[2] = 7.0
a

[3.0, 4.0, 7.0]

In [139]:
import torch
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [140]:
a[1]


tensor(1.)

In [141]:
float(a[1])


1.0

In [142]:
a[2] = 2.0
a

tensor([1., 1., 2., 1., 1.])

In [0]:
point = torch.zeros(7)
point[0] = 1.0
point[1] = 4.0
point[2] = 2.0
point[3] = 1.0
point[4] = 3.0
point[5] = 5.0
point[6] = 9.0

In [144]:
point = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0, 1.3])
point

tensor([1.0000, 4.0000, 2.0000, 1.0000, 3.0000, 5.0000, 1.3000])

In [145]:
float(point[0]), float(point[1])


(1.0, 4.0)

In [146]:
point = torch.tensor([[1.0, 4.0], [2.0, 3.0], [3.0, 8.0]])
point

tensor([[1., 4.],
        [2., 3.],
        [3., 8.]])

In [147]:
point.shape

torch.Size([3, 2])

In [149]:
point = torch.zeros(3, 4)
point

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [150]:
point = torch.FloatTensor([[1.0, 5.0], [3.0, 1.0], [9.0, 5.0]])
point

tensor([[1., 5.],
        [3., 1.],
        [9., 5.]])

In [151]:
point[0, 1]


tensor(5.)

In [152]:
point[0]

tensor([1., 5.])

In [153]:
point = torch.tensor([[8.0, 4.0], [9.0, 1.0], [4.0, 5.0]])
point.storage()


 8.0
 4.0
 9.0
 1.0
 4.0
 5.0
[torch.FloatStorage of size 6]

In [157]:
point_storage = point.storage()
point_storage[0]

8.0

In [158]:
point.storage()[1]

4.0

In [159]:
point = torch.tensor([[1.0, 3.0], [2.0, 4.0], [3.0, 3.0]])
point_storage = point.storage()
point_storage[0] = 2.0
point

tensor([[2., 3.],
        [2., 4.],
        [3., 3.]])

In [160]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()


2

In [161]:
second_point.size()

torch.Size([2])

In [162]:
second_point.shape

torch.Size([2])

In [163]:
points.stride()

(2, 1)

In [164]:
point = torch.tensor([[1.0, 5.0], [2.0, 1.0], [3.0, 5.0]])
second_point = point[1]
second_point.size()

torch.Size([2])

In [165]:
second_point.storage_offset()

2

In [166]:
second_point.stride()


(1,)

In [167]:
points = torch.tensor([[1.0, 6.0], [4.0, 0.0], [4.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  6.],
        [10.,  0.],
        [ 4.,  5.]])

In [106]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [107]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [108]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [109]:
id(points.storage()) == id(points_t.storage())


True

In [110]:
points.stride()

(2, 1)

In [111]:
points_t.stride()


(1, 2)

In [112]:
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([3, 4, 5])

In [113]:
some_tensor.stride()

(20, 5, 1)

In [114]:
some_tensor.stride()

(20, 5, 1)

In [115]:
points.is_contiguous()

True

In [116]:
points_t.is_contiguous()

False

In [117]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [118]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [119]:
points_t.stride()

(1, 2)

In [120]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [121]:
points_t_cont.stride()


(3, 1)

In [122]:
points_t_cont.storage()


 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [124]:
short_points.dtype

torch.int16

In [0]:
double_point = torch.zeros(10, 2).double()
short_point = torch.ones(10, 2).short()

In [0]:
double_point = torch.zeros(10, 2).to(torch.double)
short_point = torch.ones(10, 2).to(dtype=torch.short)


In [0]:
points = torch.randn(10, 2)
short_points = points.type(torch.short)

In [128]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [129]:
points[1:]
points[1:, :]
points[1:, 0] 

tensor([ 1.8114,  2.5930, -0.7682,  1.1087, -0.7802,  1.1813,  0.4498,  1.7422,
        -0.6671])

In [170]:
points = torch.ones(3, 6)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [0]:
points = torch.from_numpy(points_np)

In [0]:
torch.save(points, '/content/drive/My Drive/Colab Notebooks/Deep Learning/DL_ungraded_assignment4/DL_ungraded_assignment4/chap2/Input/ourpoints.t')

In [0]:
with open('/content/drive/My Drive/Colab Notebooks/Deep Learning/DL_ungraded_assignment4/DL_ungraded_assignment4/chap2/Input/ourpoints.t','wb') as f:
 torch.save(points, f)

In [0]:
point = torch.load('/content/drive/My Drive/Colab Notebooks/Deep Learning/DL_ungraded_assignment4/DL_ungraded_assignment4/chap2/Input/ourpoints.t')


In [0]:
with open('/content/drive/My Drive/Colab Notebooks/Deep Learning/DL_ungraded_assignment4/DL_ungraded_assignment4/chap2/Input/ourpoints.t','rb') as f:
 point = torch.load(f)

In [0]:
import h5py
f = h5py.File('/content/drive/My Drive/Colab Notebooks/Deep Learning/DL_ungraded_assignment4/DL_ungraded_assignment4/chap2/Input/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [0]:
f = h5py.File('/content/drive/My Drive/Colab Notebooks/Deep Learning/DL_ungraded_assignment4/DL_ungraded_assignment4/chap2/Input/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[1:]

In [0]:
last_points = torch.from_numpy(dset[1:])
f.close()
last_points = torch.from_numpy(dset[1:])


In [0]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 6.0], [3.0, 9.0]],
device='cuda')

In [0]:
points_gpu = points.to(device='cuda')

In [0]:
points_gpu = points.to(device='cuda:0')

In [0]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')

In [0]:
points_gpu = points_gpu + 4

In [0]:
points_cpu = points_gpu.to(device='cpu')

In [0]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()


In [0]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

In [0]:
a = torch.ones(3, 4)
a_t = a.transpose(0, 1)

In [0]:
a = torch.ones(3, 2)


In [194]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])