**Multi head classification (multi class classification) with Keras**

In [0]:
# Import required libraries
import os
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from keras.wrappers.scikit_learn import KerasClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Model, load_model
from sklearn.model_selection import KFold
from keras.layers import Input, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras import regularizers
from sklearn.metrics import confusion_matrix, f1_score, recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from google.colab import drive
from keras.models import Sequential
from keras.layers import Dense,Dropout, Flatten
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from keras.optimizers import Adam,sgd
from sklearn.metrics import mean_absolute_error
from keras import layers, metrics
import keras

In [3]:
drive.mount('/content/drive')
data = pd.read_csv("/content/drive/My Drive/data/Glass.csv",sep=',')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
data.head()

refractive_index  Sodium  Magnesium  ...  Barium  Iron  Glass_Type
0           1.52101   13.64       4.49  ...     0.0   0.0           1
1           1.51761   13.89       3.60  ...     0.0   0.0           1
2           1.51618   13.53       3.55  ...     0.0   0.0           1
3           1.51766   13.21       3.69  ...     0.0   0.0           1
4           1.51742   13.27       3.62  ...     0.0   0.0           1

[5 rows x 10 columns]

In [9]:
# Check for the null values
data.isna().sum()

refractive_index    0
Sodium              0
Magnesium           0
Aluminum            0
Silicon             0
Potassium           0
Calcium             0
Barium              0
Iron                0
Glass_Type          0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   refractive_index  214 non-null    float64
 1   Sodium            214 non-null    float64
 2   Magnesium         214 non-null    float64
 3   Aluminum          214 non-null    float64
 4   Silicon           214 non-null    float64
 5   Potassium         214 non-null    float64
 6   Calcium           214 non-null    float64
 7   Barium            214 non-null    float64
 8   Iron              214 non-null    float64
 9   Glass_Type        214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [14]:
# Checking shape of dataset
data.shape

(214, 10)

In [8]:
# Total types of glasses
data['Glass_Type'].unique()

array([1, 2, 3, 5, 6, 7])

In [0]:
# Defining the input and output layer of Keras Model
op_layer = data['Glass_Type']
ip_layer = data.drop(columns=['Glass_Type'])

In [13]:
# Encode the lables present in output layer

encode = LabelEncoder()
encode.fit(op_layer)
encode_op = encode.transform(op_layer)
data_op = np_utils.to_categorical(encode_op)
print(data_op)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [0]:
# Split the data into test and train
x_train,x_test,y_train,y_test = train_test_split(ip_layer,data_op,test_size=.3,random_state=0)

In [0]:
# Define a NN model for multiclass classification

def multiClass_algo(x_train,x_test,y_train,y_test):
    l = Sequential()
    l.add(Dense(10, activation="relu",input_shape=(9,)))
    l.add(Dropout(0.2))
    l.add(Dense(8, activation="relu"))
    l.add(Dropout(0.1))
    l.add(Dense(6,activation='softmax'))
    l.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    l.fit(x_train, y_train, epochs=500)
    res = l.evaluate(x_test, y_test)
    return res

In [67]:
# Run the model
multiClass_algo(x_train,x_test,y_train,y_test)

Epoch 1/500
149/149 [==============================] - 0s 705us/step - loss: 14.0038 - accuracy: 0.1208
Epoch 2/500
149/149 [==============================] - 0s 52us/step - loss: 13.6596 - accuracy: 0.1745
Epoch 3/500
149/149 [==============================] - 0s 60us/step - loss: 13.2935 - accuracy: 0.1745
Epoch 4/500
149/149 [==============================] - 0s 60us/step - loss: 12.2407 - accuracy: 0.1544
Epoch 5/500
149/149 [==============================] - 0s 83us/step - loss: 11.5573 - accuracy: 0.1409
Epoch 6/500
149/149 [==============================] - 0s 60us/step - loss: 10.2309 - accuracy: 0.1745
Epoch 7/500
149/149 [==============================] - 0s 59us/step - loss: 10.0380 - accuracy: 0.2081
Epoch 8/500
149/149 [==============================] - 0s 59us/step - loss: 8.7313 - accuracy: 0.1611
Epoch 9/500
149/149 [==============================] - 0s 74us/step - loss: 8.3309 - accuracy: 0.1477
Epoch 10/500
149/149 [==============================] - 0s 61us/step - los

[1.0708184590706458, 0.6307692527770996]