In [19]:
import tensorflow as tf
print(tf.add(3, 2))
print(tf.add([3, 2], [3, 4]))
print(tf.square(6))
print(tf.reduce_sum([2, 1, 3]))
print(tf.square(2) + tf.square(3))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([6 6], shape=(2,), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [20]:
tmp = tf.matmul([[1]], [[2, 3]])
print(tmp)
print(tmp.shape)
print(tmp.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [21]:
import numpy as np
arr = np.ones([9, 8])
print("numpy array -> Tensors")
tensor = tf.multiply(arr, 42)
print(tensor)
print("Tensors -> numpy array method 1")
print(np.add(tensor, 1))
print("Tensor -> numpy array method 2")
print(tensor.numpy())

numpy array -> Tensors
tf.Tensor(
[[42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]], shape=(9, 8), dtype=float64)
Tensors -> numpy array method 1
[[43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43. 43.]]
Tensor -> numpy array method 2
[[42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42. 42. 42. 4

In [22]:
tmp = tf.random.uniform([9, 8])
print("GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))
print("Tensor on GPU #0:  "),
print(tmp.device.endswith('GPU:0'))

GPU available: 
[]
Tensor on GPU #0:  
False


In [23]:
import time

def time_matmul(y):
  start = time.time()
  for loop in range(10):
    tf.matmul(y, y)
  result = time.time()-start
  print("10 loops: {:0.2f}ms".format(1000*result))

# Forcing execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  y = tf.random.uniform([1000, 1000])
  assert y.device.endswith("CPU:0")
  time_matmul(y)

# Forcing execution on GPU #0 if available
if tf.config.experimental.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    y = tf.random.uniform([1000, 1000])
    assert y.device.endswith("GPU:0")
    time_matmul(y)

On CPU:
10 loops: 329.03ms


In [24]:
dataset_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])
import tempfile
_, file = tempfile.mkstemp()
with open(file, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)
dataset_file = tf.data.TextLineDataset(file)
dataset_tensors = dataset_tensors.map(tf.square).shuffle(2).batch(2)
dataset_file = dataset_file.batch(2)

print('dataset_tensors:')
for t in dataset_tensors:
  print(t)
print("\n")
print('dataset_file:')
for l in dataset_file:
  print(l)

dataset_tensors:
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  9], shape=(2,), dtype=int32)


dataset_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
